-- ==============================================================================
-- HEALTH & SAFETY MANAGEMENT SYSTEM - DATABASE SCHEMA (SUPABASE POSTGRESQL)
-- UNIFIED SINGLE TABLE SCHEMA: OBSERVATIONS (CONSOLIDATED OBSERVATION & TASK)
-- ==============================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==============================================================================
-- 1. REFERENCE EXISTING TABLES
-- (The user already has 'departments' and 'public.users' tables in database)
-- ==============================================================================

-- Existing departments table structure:
-- dept_id BIGINT PRIMARY KEY
CREATE TABLE IF NOT EXISTS public.departments (
    dept_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(20) UNIQUE,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Existing users table structure:
-- emp_id BIGINT PRIMARY KEY
CREATE TABLE IF NOT EXISTS public.users (
    emp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    full_name TEXT NOT NULL,
    username TEXT NOT NULL UNIQUE,
    password TEXT NULL,
    department TEXT NULL,
    role TEXT NOT NULL DEFAULT 'user',
    status TEXT NOT NULL DEFAULT 'active',
    user_access TEXT NULL,
    dept_id BIGINT NULL REFERENCES public.departments(dept_id) ON DELETE SET NULL,
    mobile_number VARCHAR(20) NULL,
    retail_access TEXT NULL,
    position TEXT NULL
);

-- ==============================================================================
-- 2. UNIFIED OBSERVATIONS TABLE (OBSERVATION & TASK CONSOLIDATED)
-- Observation and task are the same: observer logs hazard & assigns task directly to user.
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.observations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    created_by BIGINT NOT NULL REFERENCES public.users(emp_id) ON DELETE RESTRICT,
    dept_id BIGINT NOT NULL REFERENCES public.departments(dept_id) ON DELETE RESTRICT,
    area VARCHAR(255) NOT NULL,
    observation_text TEXT NOT NULL,
    solution_text TEXT,
    priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    risk_min NUMERIC(3, 1) NOT NULL DEFAULT 3.0,
    risk_max NUMERIC(3, 1) NOT NULL DEFAULT 6.0,
    assigned_to BIGINT NOT NULL REFERENCES public.users(emp_id) ON DELETE RESTRICT,
    due_date TIMESTAMPTZ NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'ASSIGNED' CHECK (status IN (
        'OPEN', 
        'ASSIGNED', 
        'IN_PROGRESS', 
        'SUBMITTED_FOR_REVIEW', 
        'REWORK_REQUIRED', 
        'COMPLETED', 
        'OVERDUE', 
        'CLOSED'
    )),
    corrective_action TEXT,
    rework_reason TEXT,
    is_personal BOOLEAN DEFAULT FALSE NOT NULL,
    closed_by BIGINT REFERENCES public.users(emp_id) ON DELETE SET NULL,
    closed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    completed_by BIGINT REFERENCES public.users(emp_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ==============================================================================
-- 3. OBSERVATION PHOTOS TABLE (Hazard photos & Corrective proof photos)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.observation_photos (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    observation_id UUID NOT NULL REFERENCES public.observations(id) ON DELETE CASCADE,
    photo_url TEXT NOT NULL,
    file_name VARCHAR(255),
    photo_type VARCHAR(50) NOT NULL DEFAULT 'INITIAL' CHECK (photo_type IN ('INITIAL', 'CORRECTIVE')),
    uploaded_by BIGINT REFERENCES public.users(emp_id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ==============================================================================
-- 4. NOTIFICATIONS TABLE (Alerts for Assignees & Observers)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id BIGINT NOT NULL REFERENCES public.users(emp_id) ON DELETE CASCADE,
    observation_id UUID REFERENCES public.observations(id) ON DELETE CASCADE,
    notification_type VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ==============================================================================
-- 5. OBSERVATION MESSAGES (Realtime Communication on Observation)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.observation_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    observation_id UUID NOT NULL REFERENCES public.observations(id) ON DELETE CASCADE,
    sender_id BIGINT NOT NULL REFERENCES public.users(emp_id) ON DELETE RESTRICT,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ==============================================================================
-- 6. OBSERVATION HISTORY & MULTI-CYCLE REWORK TRACKING
-- Tracks every attempt, remarks, refusal reasons, and decisions in loop cycles (e.g. 5+ loops)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS public.observation_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    observation_id UUID NOT NULL REFERENCES public.observations(id) ON DELETE CASCADE,
    action_type VARCHAR(50) NOT NULL, -- 'CREATED', 'ASSIGNED', 'SUBMITTED_FOR_REVIEW', 'REWORK_REQUIRED', 'COMPLETED', 'CLOSED'
    attempt_number INT NOT NULL DEFAULT 1,
    description TEXT NOT NULL,
    rework_reason TEXT,
    performed_by BIGINT NOT NULL REFERENCES public.users(emp_id) ON DELETE RESTRICT,
    previous_status VARCHAR(50),
    new_status VARCHAR(50),
    photos JSONB DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ==============================================================================
-- 7. INDEXES FOR PERFORMANCE
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_observations_dept ON public.observations(dept_id);
CREATE INDEX IF NOT EXISTS idx_observations_created_by ON public.observations(created_by);
CREATE INDEX IF NOT EXISTS idx_observations_assigned_to ON public.observations(assigned_to);
CREATE INDEX IF NOT EXISTS idx_observations_status ON public.observations(status);
CREATE INDEX IF NOT EXISTS idx_observations_due_date ON public.observations(due_date);
CREATE INDEX IF NOT EXISTS idx_observations_priority ON public.observations(priority);
CREATE INDEX IF NOT EXISTS idx_observation_photos_obs ON public.observation_photos(observation_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread ON public.notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_observation_messages_obs ON public.observation_messages(observation_id);
CREATE INDEX IF NOT EXISTS idx_obs_history_obs_id ON public.observation_history(observation_id);
CREATE INDEX IF NOT EXISTS idx_obs_history_performed_by ON public.observation_history(performed_by);
CREATE INDEX IF NOT EXISTS idx_obs_history_created_at ON public.observation_history(created_at);

-- ==============================================================================
-- 7. TRIGGERS AND FUNCTIONS
-- ==============================================================================

-- Automatic Risk Factor calculation based on priority
CREATE OR REPLACE FUNCTION trg_calculate_observation_risk()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.priority = 'LOW' THEN
        NEW.risk_min := 1.0;
        NEW.risk_max := 3.0;
    ELSIF NEW.priority = 'MEDIUM' THEN
        NEW.risk_min := 3.0;
        NEW.risk_max := 6.0;
    ELSIF NEW.priority = 'HIGH' THEN
        NEW.risk_min := 6.0;
        NEW.risk_max := 9.0;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_observation_risk ON public.observations;
CREATE TRIGGER set_observation_risk
    BEFORE INSERT OR UPDATE OF priority ON public.observations
    FOR EACH ROW
    EXECUTE FUNCTION trg_calculate_observation_risk();

-- Updated_at timestamp auto-refresh
CREATE OR REPLACE FUNCTION trg_update_observation_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS update_observations_modtime ON public.observations;
CREATE TRIGGER update_observations_modtime
    BEFORE UPDATE ON public.observations
    FOR EACH ROW
    EXECUTE FUNCTION trg_update_observation_timestamp();

-- Check Overdue function (can be invoked via scheduled cron or query)
CREATE OR REPLACE FUNCTION check_overdue_observations()
RETURNS INTEGER AS $$
DECLARE
    overdue_count INTEGER := 0;
    r RECORD;
BEGIN
    FOR r IN 
        SELECT o.id, o.observation_number, o.assigned_to, o.created_by, o.due_date, u.full_name as assignee_name
        FROM public.observations o
        JOIN public.users u ON o.assigned_to = u.emp_id
        WHERE o.due_date < NOW() 
          AND o.status NOT IN ('COMPLETED', 'CLOSED', 'OVERDUE')
    LOOP
        UPDATE public.observations 
        SET status = 'OVERDUE', updated_at = NOW() 
        WHERE id = r.id;

        INSERT INTO public.notifications (user_id, observation_id, notification_type, title, message)
        VALUES (
            r.created_by,
            r.id,
            'TASK_OVERDUE',
            '⚠ Overdue Action: ' || r.observation_number,
            'Observation task assigned to ' || r.assignee_name || ' has exceeded its due date without completion.'
        );

        overdue_count := overdue_count + 1;
    END LOOP;
    RETURN overdue_count;
END;
$$ LANGUAGE plpgsql;

-- ==============================================================================
-- 8. ROW LEVEL SECURITY (RLS) POLICIES
-- ==============================================================================
ALTER TABLE public.observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.observation_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.observation_messages ENABLE ROW LEVEL SECURITY;
-- Disable RLS on observation_history and grant all access to prevent 42501 Unauthorized errors
ALTER TABLE public.observation_history DISABLE ROW LEVEL SECURITY;
GRANT ALL ON TABLE public.observation_history TO anon, authenticated, service_role;

-- Allow authenticated and anon (via key) full read and write for the system
DROP POLICY IF EXISTS "Observations allow all" ON public.observations;
CREATE POLICY "Observations allow all" ON public.observations FOR ALL USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Observation photos allow all" ON public.observation_photos;
CREATE POLICY "Observation photos allow all" ON public.observation_photos FOR ALL USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Notifications allow all" ON public.notifications;
CREATE POLICY "Notifications allow all" ON public.notifications FOR ALL USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "Observation messages allow all" ON public.observation_messages;
CREATE POLICY "Observation messages allow all" ON public.observation_messages FOR ALL USING (TRUE) WITH CHECK (TRUE);
CREATE POLICY "Officer self tasks allow all" ON public.officer_self_tasks FOR ALL USING (TRUE) WITH CHECK (TRUE);

